---

- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/default.yaml
  tasks:
  - name: Create Dir to Downlaod Tomcat.
    file: path=/opt/apps/tomcat state=directory

  - name: Install Java 1.8
    yum: name=java-1.8.0-openjdk state=present

  - name: Download Tomcat
    get_url: url=http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz dest=/opt/apps/tomcat.tar.gz mode=0755

  - name: Extract Tomcat
    command: "tar zxf /opt/apps/tomcat.tar.gz  -C /opt/apps/tomcat --strip-components 1"

  - name: Copy Index Page Files
    copy: src=wars dest=/opt/apps/tomcat/webapps/ mode=0644
    notify:
    - Restart Tomcat

  - name: copy war file to tomcat
    copy: src=wars/addressbook.war dest= /opt/apps/tomcat/webapps/ mode=0644

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/apps/tomcat/bin/catalina.sh start"
